name             'lissa'
maintainer       'ONEAgency'
maintainer_email 'gent@one-agency.be'
license          'All rights reserved'
description      'Installs/Configures LISSA'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

recipe           'lissa', 'Main LISSA configuration'
recipe           'lissa::worker', 'Worker role cookbook'
recipe           'lissa::database', 'Database role cookbook'
recipe           'lissa::web', 'Web role cookbook'
recipe           'lissa::drupal-distro', 'Drupal LISSA kickstarter distribution installation recipe'

depends 'apache2'
depends 'php'
depends 'composer'
depends 'mysql'
depends 'drush'
depends 'phing'
depends 'nginx'
depends 'openssh'
depends 'chef-client'
depends 'ssh_known_hosts'
depends 'git'
depends 'curl'
depends 'chef-dotdeb'
depends 'hostsfile'
depends 'rabbitmq'
depends 'python'
depends 'supervisor'
depends 'vim'
